---

- hosts: all
  become: true
  tasks:

# Debian based OS

  - name: APT >> update repo cache
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: APT >> install net-tools package
    apt:
      name: net-tools
      state: latest
    when: ansible_facts['os_family'] == "Debian"

# RedHat based OS

  - name: YUM >> update repo cache
    yum:
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: YUM >> install net-tools package
    yum:
      name: net-tools
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
